name: var-1
on: push

env:
  level: workflow

jobs:
  get-env1:
    runs-on: ubuntu-latest
    steps:
      - name: check env1
        run: echo "LEVEL ${{ env.level }}"
  get-env2:
    runs-on: ubuntu-latest
    env:
      level: job
    steps:
      - name: check env2
        run: echo "LEVEL ${{ env.level }}"
  get-env3:
    runs-on: ubuntu-latest
    env:
      level: job
    steps:
      - name: check env3
        run: echo "LEVEL ${{ env.level }}"
        env:
          level: org
  get-env:
    runs-on: ubuntu-latest
    env:
      level: job
    steps:
      - name: create env
        run: echo "level=job" >> $GITHUB_ENV
      - name: check env
        run: echo "LEVEL ${{ env.level }}"
  get-env-already:
    runs-on: ubuntu-latest
    steps:
      - name: get var
        run: echo ${{ vars.level}}
