name: issue-workflow
on:
  issue:
    types: [opened]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo hello world
      - name: step 2
        run: |
          echo it is step 2 
          echo github actions
