name: pull-request-workflow
on:
  pull_request:
    types: [opened]

jobs:
  pull-request-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo step2
          echo step2 hello world
